/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsDocIdRouteImport } from './routes/docs.$docId'
import { Route as ProjectsProjectIdBoardRouteImport } from './routes/projects.$projectId.board'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDocIdRoute = DocsDocIdRouteImport.update({
  id: '/docs/$docId',
  path: '/docs/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdBoardRoute = ProjectsProjectIdBoardRouteImport.update({
  id: '/projects/$projectId/board',
  path: '/projects/$projectId/board',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs/$docId': typeof DocsDocIdRoute
  '/docs/': typeof DocsIndexRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs/$docId': typeof DocsDocIdRoute
  '/docs': typeof DocsIndexRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs/$docId': typeof DocsDocIdRoute
  '/docs/': typeof DocsIndexRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/docs/$docId'
    | '/docs/'
    | '/projects/$projectId/board'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/docs/$docId' | '/docs' | '/projects/$projectId/board'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/docs/$docId'
    | '/docs/'
    | '/projects/$projectId/board'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DocsDocIdRoute: typeof DocsDocIdRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ProjectsProjectIdBoardRoute: typeof ProjectsProjectIdBoardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$docId': {
      id: '/docs/$docId'
      path: '/docs/$docId'
      fullPath: '/docs/$docId'
      preLoaderRoute: typeof DocsDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/board': {
      id: '/projects/$projectId/board'
      path: '/projects/$projectId/board'
      fullPath: '/projects/$projectId/board'
      preLoaderRoute: typeof ProjectsProjectIdBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DocsDocIdRoute: DocsDocIdRoute,
  DocsIndexRoute: DocsIndexRoute,
  ProjectsProjectIdBoardRoute: ProjectsProjectIdBoardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
